Issue 965: Special build using pre-release of nunit.engine 4.0.0
nunit/nunit3-vs-adapter pull request #966
Opened 2022-03-24 10:01 UTC by manfred-brands

Fixes #965 

I left this as a draft PR as I don't expect it to be merged into master.
The purpose is to get a special build that can be referenced in nunit framework nunit4 developments.

As I also not aware of the changes in the engine, I have deleted several lines in `TestAdapterUtils` as those classes no longer exist.

There was one other change. The name/fullname properties of the test-run node seem to no longer exist.

I testes the nuget package with nunit framework and it allows me to run tests in VS and with `dotnet test`

2022-03-24 10:03 UTC, manfred-brands commented
Not sure if you agree with the version number, but the adapter seems to be one ahead of the engine/framework.

2022-03-24 10:20 UTC, manfred-brands commented
The build seem to not be able to find the myget package when referenced in .csproj file. Trying to add to nuget.config

2022-03-24 10:45 UTC, manfred-brands commented
@CharliePoole The engine does find the test for netcore/net6, but not for net framework.
In the debugger is shows:
```
System.ComponentModel.Win32Exception : The system cannot find the file specified--Win32Exception
The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NUnit.Engine.Services.TestAgency.GetAgent(TestPackage package)
   at NUnit.Engine.Runners.ProcessRunner.CreateAgentAndRunnerIfNeeded()
   at NUnit.Engine.Runners.ProcessRunner.Explore(TestFilter filter)
```
It seems to be looking for nunit-agent.exe binaries. I see them in the contentFiles directory.

@OsirisTerje build.cake --target=Test shows all green lines, even though it didn't find any tests.
```
No test is available in D:\3rd\NUnit\nunit3-vs-adapter\src\NUnitTestAdapterTests\bin\Debug\net46\NUnit.VisualStudio.TestAdapter.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
```

2022-03-24 10:56 UTC, OsirisTerje requested changes
This is not a major version change, so 4.3.0 is sufficient.  Also, add pre-release for now, so e.g. 4.3.0-beta.1 should do it.   And you're right, the version numbers are **not** aligned across components, and that is "By design".  :-)

2022-03-24 14:20 UTC, CharliePoole commented
@manfred-brands My guess is that you are running into nunit/nunit-console#1023, which is a pretty big one!

I just assigned you an  issue, which is a small part of a bigger part of that issue. :-)

2023-07-03 18:05 UTC, OsirisTerje commented
I assume we don't need this anymore, as 4.5 does run nunit 4.

2023-07-03 18:05 UTC, closed without merging